from __future__ import annotations

__all__ = [
    "NodeTreeBuilder",
]

from dataclasses import dataclass

import bpy.types
from bpy.types import NodeSocket

from soulstruct.eldenring.models.shaders import MatDef, SamplerGroupRole
from ..utilities import new_shader_node, new_soulstruct_node_group

from .....exceptions import MaterialImportError
from ..base_node_tree_builder import BaseNodeTreeBuilder
from ..enums import SoulstructNodeGroups

_UNSET = object()  # sentinel for "use default resolution"


@dataclass(slots=True)
class NodeTreeBuilder(BaseNodeTreeBuilder):
    """Node tree builder for Elden Ring (2022).

    Uses role-based sampler aliases (e.g. 'PRIMARY 0 Albedo', 'DETAIL 0 Normal') generated by `MatDef.from_matbin()`
    to build Blender shader node trees. Alias format is '{SamplerGroupRole.name} {role_index} {map_type}'.

    UV layer semantic names ('UVTexture0', 'UVDetail', 'UVFurAlpha', etc.) are assigned per sampler group via the
    SHADER_GROUP_UV dictionary in `soulstruct.eldenring.models.shaders`, falling back to role-based heuristics for
    unknown shaders. These semantic names ensure correct UV merging when combining FLVER submeshes.

    Shader dispatch:
        - Fur family                → ERFurShader (FUR_ALPHA for alpha/normal, PRIMARY for base material)
        - Face family (SUB_NORMALS) → ERMask3BlendNormals + ERBasicPBRShader (three blended normals)
        - DetailBlend family        → ERBasicPBRShader with detail normal blending
        - Multi-blend (MbN)         → ERBasicPBRShader with blend-mask-weighted secondary layers
        - Everything else           → ERBasicPBRShader (standard PBR)
    """

    # Type override: Elden Ring MatDef.
    matdef: MatDef

    ALBEDO_COLOR_SPACE = "Non-Color"
    USES_RG_NORMALS = True

    @property
    def _diffuse_map_color(self) -> tuple[float, ...]:
        """Get RGBA diffuse map color. Defaults to (1, 1, 1, 1).

        TODO: MATBIN field exists and does vary, but not confirmed.
        """
        color = self.get_param("g_DiffuseMapColor", default=(1.0, 1.0, 1.0)) + (1.0,)
        return tuple(float(x) for x in color)

    @property
    def _metallic_map_color(self) -> tuple[float, ...]:
        # TODO: Not sure where to find this in ER.
        return 1.0, 1.0, 1.0, 1.0

    def build(self) -> None:
        self.operator.info(f"Building Elden Ring node tree for material definition {self.matdef.name}.")

        self._initialize_node_tree()

        profile = self.matdef.profile
        family = profile.family

        try:
            if family == "Fur":
                self._build_er_fur_shader()
                return

            if profile.multi_blend_count > 1:
                blend_mask_map = self.tex_image_nodes.get("BLEND_CONTROL 0 Mask1")
                if not blend_mask_map:
                    # A handful of shaders call it BlendEdge instead - can't detect any pattern.
                    blend_mask_map = self.tex_image_nodes.get("BLEND_CONTROL 0 BlendEdge")
                if blend_mask_map:
                    self._build_er_map_multi_blend_shader(blend_mask_map, profile.multi_blend_count)
                    return

                self.operator.warning(
                    f"Could not find Mask1 or BlendEdge texture in MbN shader for {self.matdef.name} - "
                    f"falling back to standard shader. Blending will not be set up."
                )
                self._build_er_standard_shader()
                return

            if self._has_sub_normals:
                self._build_er_threenormals_shader()
                return

            if self._has_detail_textures:
                self._build_er_detailblend_shader()
                return

            # Generic builder for AMSN, Crystal, Hair, Eye, and other shader families.
            self._build_er_standard_shader()
            return
        except MaterialImportError as ex:
            self.operator.warning(
                f"Error building shader for material '{self.matdef.name}' with shader '{self.matdef.shader_stem}'. "
                f"Error:\n    {ex}"
            )

    # region Feature Detection

    @property
    def _has_sub_normals(self) -> bool:
        """True if material has SUB_NORMALS samplers (Face shaders with three blended normals)."""
        return "SUB_NORMALS 0 Normal_0" in self.tex_image_nodes

    @property
    def _has_detail_textures(self) -> bool:
        """True if material has any DETAIL role samplers (DetailBlend, some character-specific shaders).

        DETAIL samplers use the UVDetail UV layer and provide tiled albedo/normal textures that are blended with the
        primary material. This is distinct from FUR_ALPHA (fur/hair alpha) and SUB_NORMALS (face blended normals).
        """
        return bool(self.matdef.get_samplers_by_role(SamplerGroupRole.DETAIL))

    @property
    def _uses_vertex_colors_alpha(self) -> bool:
        return not (self.matdef.has_name_tag("Multi") or not (self.matdef.edge or self.matdef.alpha))

    # endregion

    # region Shared PBR Helpers

    def _er_basic_pbr_inputs(
        self,
        normal: NodeSocket | None,
        shininess: NodeSocket | None,
        *,
        mix_fac: NodeSocket | float = 0.5,
        albedo: NodeSocket | None = _UNSET,
        albedo_alpha: NodeSocket | float | None = _UNSET,
        metallic: NodeSocket | None = _UNSET,
        shininess_map: NodeSocket | None = _UNSET,
    ) -> dict[str, ...]:
        """Build the standard input dict for ``ERBasicPBRShader``.

        ``normal`` and ``shininess`` are always required explicitly. The remaining texture
        sockets default to the common resolution patterns (PRIMARY Albedo, any Metallic /
        Shininess map) but can be overridden via keyword arguments. Pass ``None`` to
        suppress a particular input.
        """
        if albedo is _UNSET:
            albedo = self._get_mixed_texture_color(r"PRIMARY \d Albedo", mix_fac)
        if albedo_alpha is _UNSET:
            albedo_alpha = self._get_mixed_texture_alpha("PRIMARY 0 Albedo")
        if metallic is _UNSET:
            metallic = self._get_mixed_texture_color(r".* \d Metallic", mix_fac)
        if shininess_map is _UNSET:
            shininess_map = self._get_mixed_texture_color(r".* \d Shininess", mix_fac)

        return {
            "Albedo Map": albedo,
            "Albedo Map Color": self._diffuse_map_color,
            "Albedo Map Color Power": 1,  # TODO
            "Albedo Map Alpha": albedo_alpha,
            "Metallic Map": metallic,
            "Metallic Map Color": self._metallic_map_color,
            "Metallic Map Color Power": 1,  # TODO
            "Metallic Map Alpha": None,
            "Normal": normal,
            "Shininess": shininess,
            "Shininess Map": shininess_map,
            # TODO: ER uses the red VC channel for something – darkening, or ambient occlusion?
            "Vertex Colors": None,
            # TODO: ER definitely uses VC alpha for true transparency for some shaders.
            "Vertex Colors Alpha": self._vc_alpha if self._uses_vertex_colors_alpha else None,
        }

    def _process_sampler_normals(self, sampler_alias: str) -> tuple[NodeSocket, NodeSocket | None]:
        """Look up a sampler by *alias*, process its tex node through the normal pipeline.

        Raises ``ValueError`` when the sampler or tex node cannot be found.
        """
        sampler = self.matdef.get_sampler_with_alias(sampler_alias)
        if not sampler:
            raise ValueError(f"{sampler_alias} sampler not found.")
        tex_node = self.tex_image_nodes.get(sampler_alias)
        if not tex_node:
            raise ValueError(f"No image texture node present for {sampler_alias}.")
        return self._process_normal_tex(tex_node, sampler.uv_layer_name)

    # endregion

    # region Shader Builders

    def _build_er_fur_shader(self):
        """Build a Blender shader for Elden Ring '[Fur]' shaders.

        Fur shaders have a unique UV layout:
          - UV0 (UVTexture0) → PRIMARY group (base material AMN)
          - UV1 (UVDetail)   → DETAIL group (detail texture AN)
          - UV2 (UVFurAlpha) → FUR_ALPHA group (fur alpha + normals AN)

        The FUR_ALPHA group's normal map drives the main BSDF normal, while its albedo provides the fur alpha mask.
        """

        # TODO: Still need to blend DETAIL samplers.

        # FUR_ALPHA AN group provides the normal and alpha.
        normal_socket, shininess_socket = self._get_mixed_texture_normals("FUR_ALPHA 0 Normal")

        self._new_bsdf_shader_node_group(
            SoulstructNodeGroups.ERFurShader,
            inputs={
                "Albedo Map": self._get_mixed_texture_color("PRIMARY 0 Albedo"),
                "Albedo Map Color": self._diffuse_map_color,
                "Albedo Map Alpha": self._get_mixed_texture_alpha("FUR_ALPHA 0 Albedo"),
                "Normal": normal_socket,
                "Shininess": shininess_socket,
                "Vertex Colors": None,
                "Vertex Colors Alpha": self._vc_alpha,
            },
            outputs={"Shader": self.output_surface},
        )

    def _build_er_map_multi_blend_shader(self, blend_mask_map: bpy.types.ShaderNodeTexImage, multi_count: int):
        """Blend between Primary and 1+ Secondary sampler groups using a Blend Control texture and UVBlend.

        The blend mask texture is white where PRIMARY should be shown and black where SECONDARY should be shown.
        UVBlend.X is a per-vertex value in [-16, 16] that is remapped to [0, 1]:
          - 0 → blend mask is maximally applied (SECONDARY shown where mask is black)
          - 1 → blend mask is fully ignored (just PRIMARY everywhere)

        For each secondary group the blend is computed in two steps per channel:
          Step 1 (mask):        Mix(fac=mask, A=SECONDARY, B=PRIMARY)
          Step 2 (UV override): Mix(fac=remapped_uv, A=step1, B=PRIMARY)

        TODO: Mb3 secondary group selection is not yet understood — only UVBlend.X is used for all groups.
        TODO: May also have an overlay normal to mix in.
        """
        # -- UVBlend setup ---------------------------------------------------------
        if "UVBlend" in self.uv_nodes:
            uv_blend_node = self.uv_nodes["UVBlend"]
        else:
            uv_blend_node = self.uv_nodes["UVBlend"] = self._new_uv_map_node("UVBlend")

        separate_uv = new_shader_node(
            self.tree,
            bpy.types.ShaderNodeSeparateXYZ,
            location=(self.UV_X, uv_blend_node.location[1] - 100),
            inputs={"Vector": uv_blend_node.outputs["UV"]},
        )

        # Remap UVBlend.X from [-16, 16] → [0, 1] (clamped).
        # 0 = apply blend mask maximally, 1 = ignore blend mask (just PRIMARY).
        remapped_uv = new_shader_node(
            self.tree,
            bpy.types.ShaderNodeMapRange,
            location=(self.UV_X + 200, uv_blend_node.location[1] - 100),
            label="Remap UVBlend",
            inputs={
                0: separate_uv.outputs["X"],  # Value
                1: -16.0,  # From Min
                2: 16.0,   # From Max
                3: 0.0,    # To Min
                4: 1.0,    # To Max
            },
            clamp=True,
        )
        uv_fac = remapped_uv.outputs[0]  # "Result"

        mask_fac = blend_mask_map.outputs["Color"]  # white=PRIMARY, black=SECONDARY

        # -- Start with PRIMARY textures -------------------------------------------
        current_albedo = self._get_mixed_texture_color("PRIMARY 0 Albedo")
        current_normal, current_shininess = self._get_mixed_texture_normals("PRIMARY 0 Normal")

        # -- Chain-blend each secondary group --------------------------------------
        for i in range(multi_count):
            blend_y = blend_mask_map.location[1] - i * 250

            # Albedo
            secondary_albedo = self._get_mixed_texture_color(f"SECONDARY {i} Albedo")
            if current_albedo is not None and secondary_albedo is not None:
                current_albedo = self._masked_blend_sockets(
                    current_albedo, secondary_albedo, blend_y, mask_fac, uv_fac, "RGBA",
                )
            elif secondary_albedo is not None:
                current_albedo = secondary_albedo

            # Normals + Shininess
            secondary_normal, secondary_shininess = self._get_mixed_texture_normals(f"SECONDARY {i} Normal")
            if current_normal is not None and secondary_normal is not None:
                current_normal = self._masked_blend_sockets(
                    current_normal, secondary_normal, blend_y - 60, mask_fac, uv_fac, "VECTOR",
                )
            elif secondary_normal is not None:
                current_normal = secondary_normal

            if current_shininess is not None and secondary_shininess is not None:
                current_shininess = self._masked_blend_sockets(
                    current_shininess, secondary_shininess, blend_y - 100, mask_fac, uv_fac, "FLOAT",
                )
            elif secondary_shininess is not None:
                current_shininess = secondary_shininess

        # -- Final BSDF -------------------------------------------------------
        inputs = self._er_basic_pbr_inputs(
            current_normal,
            current_shininess,
            albedo=current_albedo,
            albedo_alpha=self._get_mixed_texture_alpha("PRIMARY 0 Albedo"),
        )
        self._new_bsdf_shader_node_group(
            SoulstructNodeGroups.ERBasicPBRShader,
            inputs=inputs,
            outputs={"Shader": self.output_surface},
        )

    def _build_er_threenormals_shader(self):
        """Build a Blender shader for Elden Ring shaders using three blended normals.

        Used by [Face] shaders with SUB_NORMALS groups. These shaders use a Mask3 texture to blend between three
        separate normal maps on the UVSubNormals UV layer, with the primary material on UVTexture0.
        """
        mask3_map = self.tex_image_nodes["PRIMARY 0 Mask3"]

        main_normal, main_shininess = self._process_sampler_normals("PRIMARY 0 Normal")

        inputs = {
            "Primary Normal": main_normal,
            "Primary Shininess": main_shininess,
            "Mask3 Map": mask3_map.outputs["Color"],
            "Mask3 Normalization": 0.2,  # TODO: source?
        }

        for i in range(3):
            normal_socket, blue_socket = self._process_sampler_normals(f"SUB_NORMALS 0 Normal_{i}")
            assert blue_socket is not None
            inputs[f"Normal {i}"] = normal_socket
            inputs[f"Shininess {i}"] = blue_socket

        mask3_normals_blend = new_soulstruct_node_group(
            self.tree,
            SoulstructNodeGroups.ERMask3BlendNormals,
            location=(self.POST_TEX_X, mask3_map.location[1]),
            inputs=inputs,
        )

        pbr_inputs = self._er_basic_pbr_inputs(
            mask3_normals_blend.outputs["Normal"],
            mask3_normals_blend.outputs["Shininess"],
            albedo=self._get_mixed_texture_color("PRIMARY 0 Albedo"),
            albedo_alpha=1.0,  # TODO: assuming no skin alpha
            metallic=None,
            shininess_map=None,
        )
        self._new_bsdf_shader_node_group(
            SoulstructNodeGroups.ERBasicPBRShader,
            inputs=pbr_inputs,
            outputs={"Shader": self.output_surface},
        )

        # TODO: Auto-setting UV scale to 20.0.
        tex_node = self.tex_image_nodes["SUB_NORMALS 0 Normal_0"]
        uv_scale_node = tex_node.inputs["Vector"].links[0].from_node
        if uv_scale_node:
            uv_scale_node.inputs[1].default_value = [20.0, 20.0, 1.0]

    def _build_er_detailblend_shader(self):
        """Build a Blender shader for DetailBlend family and similar shaders with DETAIL groups.

        DetailBlend shaders have:
          - UV0 (UVTexture0) → PRIMARY group (base material AMN), also used by group_8
          - UV1 (UVDetail)   → DETAIL groups (detail AN layers: groups 2/3/4/7)
          - UV2 (UVTexture1) → SECONDARY group ([S2] second skin layer, if present)

        All available detail normals are chain-mixed into the primary normal.  Layers whose
        textures have no image are automatically skipped, preventing mixing with black.
        In the actual game shader, blending is driven by vertex colors or mask textures;
        here we approximate with a fixed 50% mix per layer.

        TODO: Use proper blend factor from vertex colors or Mask1 texture.
        TODO: Blend detail albedo as well, not just normals.
        TODO: Handle [S2] secondary layer.
        """
        mix_fac = 0.5  # TODO: should come from vertex colors or mask textures.

        # Primary normal.
        normal_socket, shininess_socket = self._get_mixed_texture_normals("PRIMARY 0 Normal", mix_fac)

        # Collect ALL detail normals that have images and chain-mix them into the primary.
        detail_samplers = self.matdef.get_samplers_by_role(SamplerGroupRole.DETAIL)
        detail_normal_layers: list[tuple[NodeSocket | None, float]] = []
        for sampler in detail_samplers:
            if "Normal" not in sampler.alias:
                continue
            tex_node = self.tex_image_nodes.get(sampler.alias)
            if tex_node and tex_node.image:
                dn_socket, _ = self._process_normal_tex(tex_node, sampler.uv_layer_name)
                detail_normal_layers.append((dn_socket, mix_fac))

        if normal_socket is not None and detail_normal_layers:
            normal_socket = self._chain_mix_sockets(
                normal_socket, detail_normal_layers, self.mix_y, "VECTOR",
            )

        inputs = self._er_basic_pbr_inputs(normal_socket, shininess_socket, mix_fac=mix_fac)
        self._new_bsdf_shader_node_group(
            SoulstructNodeGroups.ERBasicPBRShader,
            inputs=inputs,
            outputs={"Shader": self.output_surface},
        )

    def _build_er_standard_shader(self):
        """Standard Elden Ring PBR workflow for non-specialized shader families.

        Handles C[AMSN], M[AMSN], C[Crystal], C[Hair], C[Eye], and most character-specific shaders. These typically
        use UVTexture0 for all sampler groups, with UV1 (UVTexture1) reserved for non-sampler data (tangent space,
        refraction coordinates, etc.).
        """
        # TODO: Mixing Fac should come from Blend01 map, if present.
        mix_fac = 0.5

        normal_socket, shininess_socket = self._get_mixed_texture_normals("PRIMARY 0 Normal", mix_fac)

        inputs = self._er_basic_pbr_inputs(normal_socket, shininess_socket, mix_fac=mix_fac)
        self._new_bsdf_shader_node_group(
            SoulstructNodeGroups.ERBasicPBRShader,
            inputs=inputs,
            outputs={"Shader": self.output_surface},
        )

    # endregion
